---
title: "Albumin usage in HVI ICUs"
author: "Brian Gulbis"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(forcats)
library(lubridate)
library(edwr)
library(themebg)

dir_raw <- "../data/raw"
hvi_icu <- c("HH CCU", "HH CVICU", "HH HFIC")

hvi_pts <- read_data(dir_raw, "location", FALSE) %>%
    as.locations() %>%
    filter(unit.name %in% hvi_icu) %>%
    distinct(millennium.id, unit.name)

unit_num <- hvi_pts %>%
    count(unit.name) %>%
    rename(pts_n = n)

meds <- read_data(dir_raw, "meds-inpt", FALSE) %>%
    as.meds_inpt()

albumin <- meds %>%
    filter(med == "albumin human")

actions <- read_data(dir_raw, "orders-actions", FALSE) %>%
    as.order_action() %>%
    filter(action.type == "Order")

details <- read_data(dir_raw, "orders-details", FALSE) %>%
    as.order_detail()

orders <- actions %>%
    full_join(details, by = c("millennium.id", "order.id", "order"))

# x <- distinct(albumin, med.location)
```

```{r}
albumin %>%
    distinct(millennium.id, med.location) %>%
    count(med.location) %>%
    inner_join(unit_num, by = c("med.location" = "unit.name")) %>%
    mutate(pct = n / pts_n * 100) %>%
    select(-pts_n) %>%
    rename(Location = med.location, N = n, `%` = pct) %>%
    knitr::kable(caption = "Number of patients receiving albumin by ICU", digits = 1)
```

```{r}
albumin_n <- albumin %>%
    filter(med.location %in% hvi_icu) %>%
    distinct(event.id, med.location) %>%
    count() %>%
    rename(total_n = n)

albumin %>%
    filter(med.location %in% hvi_icu) %>%
    distinct(event.id, med.location) %>%
    count(med.location) %>%
    mutate(total_n = albumin_n$total_n) %>%
    # inner_join(unit_num, by = c("med.location" = "unit.name")) %>%
    mutate(pct = n / total_n * 100) %>%
    select(-total_n) %>%
    rename(Location = med.location, N = n, `%` = pct) %>%
    knitr::kable(caption = "Number of doses of albumin given in each ICU", digits = 1)
```

```{r, fig.cap="Top provider types ordering albumin in HVI ICUs", out.height="4in"}
orders %>%
    filter(order.location %in% hvi_icu) %>%
    mutate_at("order.provider.position", funs(coalesce(., action.provider.role))) %>%
    count(order.location, order.provider.position) %>%
    arrange(desc(n)) %>%
    mutate_at("order.provider.position", as_factor) %>%
    mutate_at("order.provider.position", fct_lump, n = 10) %>%
    mutate_at("order.provider.position", fct_rev) %>%
    ggplot(aes(x = order.provider.position, y = n)) +
    geom_bar(stat = "identity") +
    xlab(NULL) +
    ylab("Number of Orders") +
    facet_wrap(~ order.location) +
    coord_flip() +
    theme_bg()
```

```{r, fig.cap="Order communication type", out.height="4in"}
orders %>%
    filter(order.location %in% hvi_icu) %>%
    count(order.location, action.comm) %>%
    arrange(desc(n)) %>%
    mutate_at("action.comm", as_factor) %>%
    mutate_at("action.comm", fct_rev) %>%
    ggplot(aes(x = action.comm, y = n)) +
    geom_bar(stat = "identity") +
    xlab(NULL) +
    ylab("Number of Orders") +
    facet_wrap(~ order.location) +
    coord_flip() +
    theme_bg()

```

```{r, fig.cap="Number of orders by time of day", fig.height=6}
orders %>%
    filter(order.location %in% hvi_icu) %>%
    mutate_at("order.datetime", funs(coalesce(., action.datetime))) %>%
    mutate(hour = hour(order.datetime)) %>%
    ggplot(aes(x = hour)) +
    geom_bar() +
    facet_wrap(~ order.location, ncol = 1, scales = "free_y") +
    scale_x_continuous(NULL, breaks = seq(0, 24, 6)) +
    ylab("Number of Orders") +
    theme_bg()
```

```{r, fig.cap="Top providers ordering albumin in each HVI ICU by order type", fig.height=8}
lvl <- orders %>%
    filter(order.location %in% hvi_icu) %>%
    mutate_at("order.provider", funs(coalesce(., action.provider))) %>%
    count(order.provider, sort = TRUE)

orders %>%
    filter(order.location %in% hvi_icu) %>%
    mutate_at("order.provider", funs(coalesce(., action.provider))) %>%
    count(order.location, action.comm, order.provider) %>%
    arrange(desc(n)) %>%
    filter(n > 2) %>%
    mutate_at("order.provider", factor, levels = lvl$order.provider) %>%
    # mutate_at("order.provider", fct_lump, n = 10) %>%
    mutate_at("order.provider", fct_rev) %>%
    ggplot(aes(x = order.provider, y = n, fill = action.comm)) +
    geom_bar(stat = "identity") +
    xlab(NULL) +
    ylab("Number of Orders") +
    scale_fill_discrete("Order Type") +
    facet_wrap(~ order.location, ncol = 1, scales = "free_y") +
    coord_flip() +
    theme_bg() + 
    theme(legend.position = "bottom", legend.title = element_text(color = "grey35"))
```
