---
title: "Albumin Usage in HVI ICUs"
subtitle: "Exploratory Data Analysis"
author: "Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(tidyverse)
library(edwr)
library(DT)

dir_raw <- "../data/raw"
hvi_icu <- c("HH CCU", "HH CVICU", "HH HFIC")

hvi_pts <- read_data(dir_raw, "location", FALSE) %>%
    as.locations() %>%
    filter(unit.name %in% hvi_icu) %>%
    distinct(millennium.id, unit.name)

unit_num <- hvi_pts %>%
    count(unit.name) %>%
    rename(pts_n = n)

meds <- read_data(dir_raw, "meds-inpt", FALSE) %>%
    as.meds_inpt()

albumin <- meds %>%
    filter(med == "albumin human")

# x <- distinct(albumin, med.location)
```

```{r}
albumin %>%
    distinct(millennium.id, med.location) %>%
    count(med.location) %>%
    inner_join(unit_num, by = c("med.location" = "unit.name")) %>%
    mutate(pct = n / pts_n) %>%
    select(-pts_n) %>%
    datatable(caption = "Number of patients receiving albumin by ICU",
              rownames = FALSE,
              colnames = c("Location", "N", "%"),
              options = list(dom = "t")) %>%
    formatPercentage("pct", 1)
```

```{r}
albumin_n <- albumin %>%
    filter(med.location %in% hvi_icu) %>%
    distinct(event.id, med.location) %>%
    count() %>%
    rename(total_n = n)

albumin %>%
    filter(med.location %in% hvi_icu) %>%
    distinct(event.id, med.location) %>%
    count(med.location) %>%
    mutate(total_n = albumin_n$total_n) %>%
    # inner_join(unit_num, by = c("med.location" = "unit.name")) %>%
    mutate(pct = n / total_n) %>%
    select(-total_n) %>%
    datatable(caption = "Number of doses of albumin given in each ICU",
              rownames = FALSE,
              colnames = c("Location", "N", "%"),
              options = list(dom = "t")) %>%
    formatPercentage("pct", 1)
```


